# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  source:  
    description: 'Main LaTeX file to build'
    required: true
    default: 'main.tex'
  engine:
    description: "TeX engine to use to build the document."
    required: false
    default: "pdflatex"
  working-directory:
    description: "Directory to run the LaTeX build in."
    required: false
    default: ""

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ toJson(inputs) }}
